{% set name = "wagtailtables" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wagtailtables-{{ version }}.tar.gz
  sha256: 45bfcfda12e56e479fae05e0438efb5026928793d588c9d08101d5af27021544

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - wagtail >=3.0

test:
  imports:
    - wagtailtables
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/overcast/wagtailtables/
  summary: jSpreadsheet table blocks for Wagtail
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
