{% set name = "wagtailtables" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/wagtailtables-{{ version }}.tar.gz
  sha256: fc05a63a659597706cfd4eb82c9a18fa6678addb50c500ab28ea3534f19d4c43

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - wagtail >=7.0

test:
  imports:
    - wagtailtables
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/overcast/wagtailtables/
  summary: jSpreadsheet table blocks for Wagtail
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
